direction: right
vars {
      B1: "#2E7D32"
      B2: "#66BB6A"
      B3: "#A5D6A7"
      B4: "#C5E1A5"
      B5: "#E6EE9C"
      B6: "#FFF59D"
      AA2: "#0D47A1"
      AA4: "#42A5F5"
      AA5: "#90CAF9"
      AB4: "#F44336"
      AB5: "#FFCDD2"
}
AXI_L_M {
    style.fill: "#2E7D32"
}

UART {
    tooltip: s
    style.fill: "#2E7D32"

    AXI_L_S {
    }

    FIFO {

    }

    UART_RX {

    }

    AXI_L_S -> FIFO
    FIFO <-> UART_RX
}
AXI_L_M <-> UART.AXI_L_S: kek3
AXI_L_M <-> UART.AXI_L_S: kek2